name: Sync to Hugging Face Spaces
on:
  push:
    branches: [main]
  # Allows manual triggering
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Push the main branch to the Hugging Face Space repository
          git push --force https://JapjeetSingh17:$HF_TOKEN@huggingface.co/spaces/JapjeetSingh17/visafe-api main
